# Generated by Django 4.0.7 on 2023-03-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Average_rent_per_unit', models.BigIntegerField(blank=True, choices=[('600', '600'), ('700', '700'), ('800', '800'), ('900', '900'), ('1000', '1000')])),
                ('First_Mtg_Interest_Rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
