# Generated by Django 4.0.7 on 2023-03-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='Average_rent_per_unit',
            field=models.BigIntegerField(blank=True, choices=[(1, '600'), (2, '700'), (3, '800'), (4, '900'), (5, '1000')]),
        ),
    ]
