# Generated by Django 4.0.7 on 2023-04-27 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_rental_user_details_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30, null=True)),
                ('year_built', models.CharField(max_length=30, null=True)),
                ('baths', models.CharField(max_length=30, null=True)),
                ('beds', models.CharField(max_length=30, null=True)),
                ('stories', models.CharField(max_length=30, null=True)),
                ('list_price', models.CharField(max_length=30, null=True)),
                ('unit', models.CharField(max_length=30, null=True)),
                ('postal_code', models.CharField(max_length=30, null=True)),
                ('street_name', models.CharField(max_length=30, null=True)),
                ('lat', models.CharField(max_length=30, null=True)),
                ('lon', models.CharField(max_length=30, null=True)),
                ('link', models.TextField(null=True)),
                ('property_id', models.CharField(max_length=30)),
                ('tax', models.CharField(max_length=30, null=True)),
                ('insurance_rate', models.CharField(max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
