# Generated by Django 4.0.7 on 2023-04-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_favourites_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourites',
            name='fav_toggle',
            field=models.BooleanField(default=False),
        ),
    ]
