# Generated by Django 4.0.7 on 2023-05-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_favourites_fav_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourites',
            name='Cash_On_Cash_ROI',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='favourites',
            name='Cashflow_per_unit_per_month',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
