# Generated by Django 4.0.7 on 2023-04-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPrefrences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_info',
            name='Management_Rate',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
            preserve_default=False,
        ),
    ]
