# Generated by Django 4.0.7 on 2023-04-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPrefrences', '0003_remove_property_info_management_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_info',
            name='Management_Rate',
            field=models.DecimalField(decimal_places=3, default=0.05, max_digits=5),
        ),
    ]
