# Generated by Django 4.0.7 on 2023-04-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPrefrences', '0005_property_info_advertizing_cost_per_vacancy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_info',
            name='Annual_Appreciation_Rate',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property_info',
            name='Fair_Market_Value',
            field=models.DecimalField(decimal_places=2, default=374000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property_info',
            name='Management_Rate',
            field=models.DecimalField(decimal_places=3, default=0.05, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property_info',
            name='Vacancy_Rate',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=10),
        ),
    ]
