# Generated by Django 4.0.7 on 2023-04-25 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserPrefrences', '0006_alter_property_info_annual_appreciation_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pest_Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trash_Removal', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('Miscellaneous', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('Common_Area_Maintenance', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('Capital_Improvements', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('Accounting', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('Legal', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('Bad_Debts', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('Other', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Operating_Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Electricity', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('Gas', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('Lawn_Snow_Maintenance', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('Association_Fees', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Parking', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('Storage', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('Laundry_Vending', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('Other', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Financing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Mtg_Amortization_Period', models.DecimalField(decimal_places=3, default=30.0, max_digits=10)),
                ('First_Mtg_CMHC_Fee', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('Second_Mtg_Principle_Amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('Second_Mtg_Amortization_Period', models.DecimalField(decimal_places=3, default=30.0, max_digits=10)),
                ('Interest_Only_Principle_Amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('Interest_Only_Interest_Rate', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('Interest_Only_Total_Monthly_Payment', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('Other_Monthly_Financing_Costs', models.DecimalField(decimal_places=3, default=300.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Environmentals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inspections_Engineer_Report', models.DecimalField(decimal_places=3, default=700.0, max_digits=10)),
                ('Appraisals', models.DecimalField(decimal_places=3, default=700.0, max_digits=10)),
                ('Misc', models.DecimalField(decimal_places=3, default=500.0, max_digits=10)),
                ('Legal', models.DecimalField(decimal_places=3, default=600.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cash_requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deposit_made_with_Offer', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('Less_ProRation_of_Rents', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
